### ISSUE TITLE
H109 is not readable

### ISSUE THREAD

**Issue by cpaulik** [TUW-GEO/ascat#8]
H109 has porosity and ancillary flags in external files and thus can not be read like the H25 products.

@sebhahn I guess they are point data files and should be supported by pynetcf?

**Comment by sebhahn** [comment]
Yes, porosity and ancillary flags are now "static layer" and stored as (two separate) NetCDF file. At the moment I'm writing some H-SAF documentation for it. Removing both data sets from the time series data records has been done for two reasons: (1) decrease the overall file size and (2) to allow a static layer its own evolution (i.e. various versions and updates in the future). However, I'm not sure in which python package we should support reading them. Perhaps this package is still the closest one. What do you think?

**Comment by cpaulik** [comment]
Yes, I think that support in this package would be great. I would like to use porosity and advisory flags in the same manner as with the H25 product if the user gives the filenames of these files. Do you already have an internal reader for this?

**Comment by sebhahn** [comment]
No there is no internal reader since they are simple NetCDF files. The dimension definition follows the Point Data structure of the CF conventions (but uses an additional dimension (doy) besides the locations dimension).  However, reading this data sets is not the original issue here. I'll try to fix H109 and raise another issue about the static layers.

**Comment by sebhahn** [comment]
Fixed with pull request https://github.com/TUW-GEO/ascat/pull/25
